apiVersion: v1
kind: Service
metadata:
  name: emqx-ee-headless
  labels:
    app.kubernetes.io/instance: emqx-ee-headless
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: "http-management-8081"
    port: 8081
    protocol: "TCP"
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: emqx-ee
